// Package brand records which committed brand rasters were generated from
// which vector sources, so a source edited without re-running the generator is
// caught by a test instead of shipping.
//
// This is not hypothetical: the social preview the website served carried the
// upstream product's name for months because foxxycode-logo-social.svg had been
// rebranded and its PNG export never regenerated. Nothing compared the two.
//
// The lock lives at docs/assets/brand.lock.json, scripts/brand/gen.go writes it
// and TestBrandAssetsAreInSyncWithTheirSources reads it. Verifying hashes needs
// no browser, so the check runs in the ordinary test suite while the generator
// itself needs Chrome.
package brand

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"
)

// LockPath is the lock file's path relative to the repository root.
const LockPath = "docs/assets/brand.lock.json"

// Output is one generated file and the sources it was generated from.
type Output struct {
	SHA256 string   `json:"sha256"`
	From   []string `json:"from"`
}

// Lock is the whole file: the hash of every vector source and of every file
// generated from it, all paths relative to the repository root and slash
// separated.
type Lock struct {
	Comment string            `json:"comment"`
	Sources map[string]string `json:"sources"`
	Outputs map[string]Output `json:"outputs"`
}

// Comment is the note written into every lock file, for whoever opens it first.
const Comment = "Generated by `make brand`. Every hash is sha256 of the file at that path. " +
	"A mismatch means a brand source was edited without re-exporting what derives from it."

// Load reads the lock file under root.
func Load(root string) (*Lock, error) {
	data, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(LockPath)))
	if err != nil {
		return nil, err
	}
	var lock Lock
	if err := json.Unmarshal(data, &lock); err != nil {
		return nil, fmt.Errorf("brand: parse %s: %w", LockPath, err)
	}
	return &lock, nil
}

// Save writes the lock file under root, sorted and indented so a regeneration
// that changes nothing produces no diff.
func (l *Lock) Save(root string) error {
	l.Comment = Comment
	data, err := json.MarshalIndent(l, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(root, filepath.FromSlash(LockPath)), append(data, '\n'), 0o644)
}

// Hash returns the hex sha256 of the file at a repository-relative path.
//
// Text sources are hashed with carriage returns removed. This checkout is CRLF
// on Windows (core.autocrlf, and .gitattributes pins only shell scripts and
// packaging/ to LF), so the very same committed SVG is a different byte string
// on a Windows working copy than on the Linux runner - and a lock written on
// one would fail the test on the other. Rasters are hashed byte for byte:
// they are binary, git never rewrites them, and a stray CR in a PNG is a
// corrupt PNG rather than a line ending.
func Hash(root, rel string) (string, error) {
	data, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(rel)))
	if err != nil {
		return "", err
	}
	if isText(rel) {
		data = bytes.ReplaceAll(data, []byte("\r\n"), []byte("\n"))
	}
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:]), nil
}

// isText reports whether a path holds a line-ending-sensitive source.
func isText(rel string) bool {
	switch strings.ToLower(path.Ext(rel)) {
	case ".svg", ".json", ".html":
		return true
	}
	return false
}

// Verify re-hashes every path the lock names and reports the ones that no
// longer match, in a stable order. An empty result means the committed rasters
// were generated from the committed sources.
func (l *Lock) Verify(root string) []string {
	var problems []string

	check := func(rel, want, kind string) {
		got, err := Hash(root, rel)
		if err != nil {
			problems = append(problems, fmt.Sprintf("%s %s: %v", kind, rel, err))
			return
		}
		if got != want {
			problems = append(problems, fmt.Sprintf("%s %s changed since the last export (have %s, lock says %s)", kind, rel, got[:12], want[:12]))
		}
	}

	for _, rel := range sortedKeys(l.Sources) {
		check(rel, l.Sources[rel], "source")
	}
	for _, rel := range sortedKeys(l.Outputs) {
		out := l.Outputs[rel]
		check(rel, out.SHA256, "generated")
		for _, src := range out.From {
			if _, ok := l.Sources[src]; !ok {
				problems = append(problems, fmt.Sprintf("generated %s names source %s, which the lock does not record", rel, src))
			}
		}
	}
	return problems
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
